DROP TABLE IF EXISTS coupons;

CREATE TABLE coupons
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE             VARCHAR(8) UNIQUE NOT NULL,
    DISCOUNT         DECIMAL(10, 2)      NOT NULL,
    MIN_BASKET_VALUE DECIMAL(10, 2)      NOT NULL
);

CREATE UNIQUE INDEX idx_coupon_code ON coupons (CODE);

INSERT INTO coupons (CODE, DISCOUNT, MIN_BASKET_VALUE)
VALUES ('SUMMER24', 10.00, 50.00),
       ('CODE2025', 15.00, 100.00),
       ('SCHWARZ1', 20.00, 200.00);
